/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JFrame;

/**
 *
 * @author Rade
 */
public class BasicConstraintsGUI extends javax.swing.JFrame {

    /**
     * Creates new form BasicConstraintsGUI
     */
    private KeyPairGeneratorGUI parent;
    
    public BasicConstraintsGUI(KeyPairGeneratorGUI parent) {
        super("Basic Constraints");
        this.parent = parent;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cARadio = new javax.swing.JRadioButton();
        CriticalRadio = new javax.swing.JRadioButton();
        pathLen = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        OKButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        cARadio.setText("cA");

        CriticalRadio.setText("Critical");

        jLabel1.setText("PathLen");

        OKButton.setBackground(new java.awt.Color(102, 102, 255));
        OKButton.setForeground(new java.awt.Color(255, 255, 255));
        OKButton.setText("OK");
        OKButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OKButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pathLen, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addComponent(CriticalRadio)
                    .addComponent(cARadio)
                    .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(CriticalRadio)
                .addGap(45, 45, 45)
                .addComponent(cARadio)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathLen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addComponent(OKButton, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKButtonMouseClicked
        parent.criticalBC = CriticalRadio.isSelected();
        
        if (pathLen.getText().trim().equals("") == false)
            parent.pathLen = Integer.parseInt(pathLen.getText());
        
        parent.cA = cARadio.isSelected();
        parent.basicConstraints = true;
        this.setVisible(false);
        parent.setVisible(true);
                this.dispose();
                
    }//GEN-LAST:event_OKButtonMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
         
        parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CriticalRadio;
    private javax.swing.JButton OKButton;
    private javax.swing.JRadioButton cARadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField pathLen;
    // End of variables declaration//GEN-END:variables
}
