/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Rade
 */
public class KeyUsageGUI extends javax.swing.JFrame {

    /**
     * Creates new form KeyUsageGUI
     */
    private KeyPairGeneratorGUI parent;
    public KeyUsageGUI(KeyPairGeneratorGUI parent) {
        super("Key Usage");
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        digitalSignature = new javax.swing.JRadioButton();
        contentCommitment = new javax.swing.JRadioButton();
        keyEncipherment = new javax.swing.JRadioButton();
        dataEncipherment = new javax.swing.JRadioButton();
        keyAgreement = new javax.swing.JRadioButton();
        keyCertSign = new javax.swing.JRadioButton();
        crlSign = new javax.swing.JRadioButton();
        encipherOnly = new javax.swing.JRadioButton();
        decipherOnly = new javax.swing.JRadioButton();
        OKButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        digitalSignature.setText("Digital Signature");

        contentCommitment.setText("Content Commitment");

        keyEncipherment.setText("Key Encipherment");

        dataEncipherment.setText("Data Enciphermnet");

        keyAgreement.setText("Key Agreement");

        keyCertSign.setText("Key Cert Sign");

        crlSign.setText("CRL Sign");

        buttonGroup1.add(encipherOnly);
        encipherOnly.setText("Encipher Only");

        buttonGroup1.add(decipherOnly);
        decipherOnly.setText("Decipher Only");

        OKButton.setBackground(new java.awt.Color(102, 102, 255));
        OKButton.setForeground(new java.awt.Color(255, 255, 255));
        OKButton.setText("OK");
        OKButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OKButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(encipherOnly)
                    .addComponent(crlSign)
                    .addComponent(keyCertSign)
                    .addComponent(keyAgreement)
                    .addComponent(contentCommitment)
                    .addComponent(digitalSignature)
                    .addComponent(keyEncipherment)
                    .addComponent(decipherOnly)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataEncipherment, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(digitalSignature)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contentCommitment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(keyEncipherment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataEncipherment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(keyAgreement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(keyCertSign)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(crlSign)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(encipherOnly)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(decipherOnly)
                .addGap(18, 18, 18)
                .addComponent(OKButton, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKButtonMouseClicked
        parent.bitString[0] = digitalSignature.isSelected();
        parent.bitString[1] = contentCommitment.isSelected();
        parent.bitString[2] = keyEncipherment.isSelected();
        parent.bitString[3] = dataEncipherment.isSelected();
        parent.bitString[4] = keyAgreement.isSelected();
        parent.bitString[5] = keyCertSign.isSelected();
        parent.bitString[6] = crlSign.isSelected();
        parent.bitString[7] = encipherOnly.isSelected();
        parent.bitString[8] = decipherOnly.isSelected();
        parent.KeyUsage = true;
        
        this.setVisible(false);
        parent.setVisible(true);
        dispose();
    }//GEN-LAST:event_OKButtonMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
       this.setVisible(false);
        parent.setVisible(true);
         //dispose();
    }//GEN-LAST:event_formWindowClosing

    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton contentCommitment;
    private javax.swing.JRadioButton crlSign;
    private javax.swing.JRadioButton dataEncipherment;
    private javax.swing.JRadioButton decipherOnly;
    private javax.swing.JRadioButton digitalSignature;
    private javax.swing.JRadioButton encipherOnly;
    private javax.swing.JRadioButton keyAgreement;
    private javax.swing.JRadioButton keyCertSign;
    private javax.swing.JRadioButton keyEncipherment;
    // End of variables declaration//GEN-END:variables
}
